spring:
  datasource:
    name: test
    url: jdbc:mysql://47.98.206.63:3306/springboottest?serverTimezone=UTC
    username: root
    password: Root123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  messages:
    basename: i18n/login

  #禁用模板缓存，是用Ctrl+F9可以编译静态页面
  mvc:
    date-format: yyyy-MM-dd
  #    static-path-pattern: /static/**
  thymeleaf:
#    prefix: classpath:/templates/
    cache: false

  profiles:
    active: testing
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test

server:
  port: 80
---
spring:
  profiles: testing

server:
  port: 8080