spring:
  datasource:
    name: test
    url: jdbc:mysql://47.98.206.63:3306/springboottest?serverTimezone=UTC
    username: root
    password: Root123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  #mvc:
   # static-path-pattern: /static/**
  #thymeleaf:
 #   prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test


